# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-19 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Users',
        ),
    ]
